### ISSUE TITLE
Bar updates

### ISSUE THREAD

**Issue by QartemisT** [DeadlyBossMods/DeadlyBossMods#412]
Tracking list for bar releated features todo;

- [ ] Reversed sort by remaining timer [#410]
- [ ] Bar apperances per-bar (large/small) [#409]
- [ ] Support custom bar "groups" and positionings. [#360]
- [ ] All the pretty things [Me]

**Comment by MysticalOS** [comment]
- [ ] New GUI option dropdown that chooses behavior of "keep" bar types.
1. Option 1: Display amount of time the ability has been off CD as a negative number (current behavior)
2. Option 2: Pause bar when it reaches 0 (0.01 effectively) if it's type is "keep' and hold bar there. This behavior is what BW users are used to

**Comment by MysticalOS** [comment]
Expanding on 3rd bar anchor.
1. By default, plugin bars such as pvp and spelltimers should be assigned to it automatically.
2. However, the user should be able to also choose to put "Important" (user activated type 7) bars there if they want
3. Users should be able to also choose (independantly from small bar anchor option) to decide whether bars move from Tools anchor to large anchor.
